# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e57ed9959824b1efa748da46712b28626597e9dfa612af77dcb5c4d795ebc67c2a444a4b13440a839ed78746092b8402b46be7fd875ce39f9d18c021d497f46

test:
  secret_key_base: 4d075f45ac5d4cf3891a6e4cbfa088135e3040499e3f9b5b7a1b0a8658b876c6f9074001805d80cfdff5307c7d21a6864af888598a21218b8e08c6db64dede2c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
